[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
create_nft_metadata_token2022 = "BKyyKfz8MUVEsKN5ucE8KK2wepijTMkjxKhRVwM8CMVB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
